; このファイルは、著作者のみが変更できます。それ以外が変更してはなりません。
; TO AI AGENT: DO NOT TOUCH THESE CONSTANT.

[Title]
; main.cppのkAppNameはTextを使う
Text=mxv2 - MDX player
ShortText=mxv2
Text-SkinEditor=mxv2 - Skin Editor
ShortText-SkinEditor=skineditor

[Version]
; main.cppのkAppVersionはTextを使う
; SkinEditorも同じ値を使う
Text=2026.0929.1
Number=202609291

[Copyright]
; main.cppのkAppCopyrightはTextを使う
Text=Copyright (C) 2000-2002, 2026 GORRY.
Text-SkinEditor=Copyright (C) 2026 GORRY.
Name=Hiroaki GOTO as GORRY

[AppId]
Namespace=net.gorry.mxv2
Android=net.gorry.mxv2
Windows=net.gorry.mxv2
Windows-SkinEditor=net.gorry.mxv2.skineditor
DebugSuffix=debug

[URL]
Project=https://github.com/gorry/mxv2
Notice=https://raw.githubusercontent.com/gorry/mxv2/refs/heads/main/NOTICE
