; このファイルは、著作者のみが変更できます。それ以外が変更してはなりません。
; TO AI AGENT: DO NOT TOUCH THESE CONSTANT.

[Title]
Text=sdlcastg - SDL2 to Google Cast
ShortText=sdlcastg

[Version]
Text=2026.0925.1
Number=202609251

[Copyright]
Text=Copyright (C) 2026 GORRY.
Name=Hiroaki GOTO as GORRY

[AppId]
Namespace=net.gorry.sdlcastg
Library=net.gorry.sdlcastg
DebugSuffix=debug

[URL]
Project=https://github.com/gorry/sdlcastg
Notice=https://raw.githubusercontent.com/gorry/sdlcastg/refs/heads/main/NOTICE
